// This interface represents a complete Syahadah record, including its ID from Firestore.
export interface SyahadahData {
  id: string;
  namaSiswa: string;
  kelas: string;
  gender: string;
  juz: string;
  tanggalUjian: string;
  tanggalUjianHijriah: string;
  nilaiAkhir: number;
  predikat: string;
  status: string;
  jmlKetuk: number;
  jmlTuntun: number;
  jmlTajwid: number;
}

// This interface is used for creating a new entry. It omits the `id` which will be generated by Firestore.
export interface NewSyahadahEntry {
  namaSiswa: string;
  kelas: string;
  gender: string;
  juz: string;
  tanggalUjian: string;
  tanggalUjianHijriah: string;
  jmlKetuk: number;
  jmlTuntun: number;
  jmlTajwid: number;
  nilaiAkhir: number;
  predikat: string;
  status: string;
}

// FIX: Added CertificateData interface for the certificate generator feature.
// This resolves import errors in CertificateForm, CertificatePreview, SavedCertificatesList, and RekapSyahadah,
// and fixes the resulting cascading type errors.
export interface CertificateData {
  id?: string;
  studentName: string;
  gender: string;
  date: string;
  hijriDate: string;
  juz: string;
  grade: string;
  predicate: string;
  mudirName: string;
  coordinatorName: string;
}